sources:
  - name: gv2
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/70985/gardens-v2---arbitrum-sepolia/{{VERSION_ARBSEP}}
documents:
  - ./src/query/queries.graphql
