sources:
  - name: gv2
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/70985/gardens-v-2-optimism-sepolia/version/latest
documents:
  - ./src/query/queries.graphql
