sources:
  - name: gv2
    handler:
      graphql:
        # endpoint: http://localhost:8000/subgraphs/name/kamikazebr/gv2/
        endpoint: ${SUBGRAPH_URL}

documents:
  - ./src/query/factory.graphql
