/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class", '[data-theme="darkTheme"]'],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  daisyui: {
    themes: [
      {
        lightTheme: {
          primary: "#FCFFF7",
          "primary-content": "#65AD18",
          "secondary-soft": "#FFF4E6",
          "secondary-content": "#FF9500",
          "neutral-button": "#acacac",
          "neutral-content": "#252525",
          "border-neutral": "#d5d5d5",
          neutral: "#FFFFFF",
          "neutral-soft-2": "#F9F9F9",
          "neutral-soft": "#EEEEEE",
          "neutral-inverted-content": "#FFFFFF",
          "tertiary-soft": "#E5F7FA",
          "tertiary-content": "#2AAAE5",
          "tertiary-hover-content": "#166AA9",
          accent: "#37CDFA",
          "danger-button": "#EB4848",
          "danger-content": "#EB4848",
          "error-content": "#EB4848",
          //additions:
          "neutral-soft-content": "#8C8C8C",
          "primary-hover-content": "#49A612",
          "primary-soft": "#EBFBD8",
          "primary-button": "#65AD18",
          "danger-hover-content": "#D03A3A",
          "danger-soft": "#FFE6E6",
          "danger-soft-dark": "#442121",
          "warning-content": "#FF9500",
        },
        darkTheme: {
          primary: "#1A1A1A",
          "primary-content": "#63B693",
          "secondary-soft-dark": "#362510",
          "secondary-content": "#FF9500",
          "neutral-button": "#ACACAC",
          "neutral-content": "#EEEEEE",
          "border-neutral": "#d5d5d5",
          neutral: "#252525",
          "neutral-soft-2": "#F9F9F9",
          "neutral-soft": "#EEEEEE",
          "neutral-inverted-content-dark": "#252525",
          "tertiary-soft": "#E5F7FA",
          "tertiary-content": "#2AAAE5",
          "tertiary-hover-content": "#166AA9",
          accent: "#37CDFA",
          "danger-button": "#EB4848",
          "danger-content": "#eb4848",
          "error-content": "#EB4848",
          //additions:
          "neutral-soft-content": "#ACACAC",
          "primary-hover-content": "#58A885",
          "primary-soft-dark": "#1A1A1A",
          "primary-button": "#3c5b4b",
          "danger-hover-content": "#E57373",
          "danger-soft": "#FFE6E6",
          "warning-content": "#E28400",
          "dark-chart-support": "#88B358",
          "light-chart-support": "#A8E066",
        },
      },
    ],
    darkTheme: false,
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
  },
  theme: {
    extend: {
      fontFamily: {
        press: ["var(--font-inter)"],
        chakra: ["var(--font-chakra)"],
        mono: ["Chakra Petch", "monospace"],
      },
      colors: {
        //added color for the our daisy - lightTheme
        "neutral-soft-content": "#8c8c8c",
        "neutral-button": "#acacac",
        "neutral-inverted-content": "#ffffff",
        "neutral-inverted-content-dark": "#252525",
        "neutral-soft": "#eeeeee",
        "neutral-soft-2": "#F9F9F9",
        "secondary-soft": "#FFF4E6",
        "secondary-button": "#FF9500",
        "secondary-soft-dark": "#362510",
        "secondary-hover-content": "#d27c03",
        "tertiary-content": "#2AAAE5",
        "tertiary-hover-content": "#166AA9",
        "tertiary-button": "#2AAAE5",
        "tertiary-dark": "#083137",
        "border-neutral": "#d5d5d5",
        "tertiary-soft": "#e5f7fa",
        "primary-hover-content": "#307707",
        "primary-button": "#65ad18",
        "primary-soft": "#EBFBD8",
        "primary-soft-dark": "#1A1A1A",
        "danger-hover-content": "#ad0000",
        "danger-button": "#e74b4d",
        "danger-content": "#EB4848",
        "danger-soft": "#FFE6E6",
        "danger-soft-dark": "#360C0A",
        "secondary-button": "#FF9500",
        "tertiary-button": "#2AAAE5",
        "primary-dark-base": "#3f8f65",
        "primary-dark-hover": "#58a885",
        "primary-dark-border": "#3f8f65",
        "primary-dark-border-hover": "#74c898",
        "primary-dark-text": "#63b693",
        "primary-dark-text-hover": "#c9f1db",
        "disabled-dark-button": "#474747",
        "disabled-dark-text": "#8a8888",
        "secondary-dark-base": "#d97706",
        "secondary-dark-hover": "#f59e0b",
        "secondary-dark-border": "#d97706",
        "secondary-dark-border-hover": "#fb923c",
        "secondary-dark-text": "#ffe6b3",
        "secondary-dark-text-hover": "#fff0d0",
        "danger-dark-base": "#eb4848",
        "danger-dark-hover": "#fe6868",
        "danger-dark-border": "#eb4848",
        "danger-dark-border-hover": "#ff6a6a",
        "danger-dark-text": "#ffd0d0",
        "danger-dark-text-hover": "#fff6f6",
        "tertiary-dark-text": "#8dd9f5",
        "tertiary-dark-text-hover": "#c4ecfb",
        "tertiary-dark-border": "#3abde6",
        "tertiary-dark-border-hover": "#72d3f0",
        "tertiary-dark-base": "#125c88",
        "tertiary-dark-hover": "#1d7fb5",
        "dark-chart-support": "#88B358",
        "light-chart-support": "#A8E066",
      },
      transitionProperty: {
        height: "height",
        spacing: "margin, padding",
      },
    },
  },
  plugins: [require("daisyui")],
};
