import clouds1_ from "./clouds1.svg";
import clouds2_ from "./clouds2.svg";
import commImg_ from "./CommunityImage.png";
import ecosystem_ from "./ecosystem.png";
import gardenFlower_ from "./garden-flower.svg";
import gardenHeader_ from "./garden-header.svg";
import gardenLand_ from "./gardenLand.svg";
import grass_ from "./Grass.svg";
import grassBrown_ from "./GrassBrown.svg";
import grassLarge_ from "./GrassLarge.svg";
import groupFlowers_ from "./Groupflowers.svg";
import honeyIcon_ from "./honeyIcon.svg";
import tree4_ from "./LongTree.svg";
import newLogo_ from "./NewLogo.png";
import blueLand_ from "./PoolBlueGrass.svg";
import proposalImg_ from "./ProposalImage.png";
import tree1_ from "./TreeOne.svg";
import tree3_ from "./TreeThree.svg";
import tree2_ from "./TreeTwo.svg";
import walletIcon_ from "./WalletIcon.svg";
import flowers_ from "./yellow-blue-flowers.svg";

export const clouds1 = clouds1_;
export const clouds2 = clouds2_;
export const gardenHeader = gardenHeader_;
export const gardenLand = gardenLand_;
export const honeyIcon = honeyIcon_;
export const gardenFlower = gardenFlower_;
export const flowers = flowers_;
export const newLogo = newLogo_;
export const tree1 = tree1_;
export const tree2 = tree2_;
export const tree3 = tree3_;
export const tree4 = tree4_;
export const grass = grass_;
export const grassLarge = grassLarge_;
export const grassBrown = grassBrown_;
export const walletIcon = walletIcon_;
export const blueLand = blueLand_;
export const commImg = commImg_;
export const groupFlowers = groupFlowers_;
export const ecosystem = ecosystem_;
export const proposalImg = proposalImg_;

export { GardensLogo } from "./GardensLogo";
