name: Bug
description: Report a problem or unexpected behavior in the Gardens app.
title: "[Bug]: "
labels:
  - bug
issue-type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue. Please provide as much detail as possible so we can reproduce and fix the problem quickly.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the bug.
      placeholder: Transaction fails when signing proposal
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: List each step needed to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What actually happened? Include full error messages when possible.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about where this occurred.
      placeholder: |
        - App version / commit: ...
        - Browser or device: ...
        - Network / chain: ...
        - Wallet: ...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Logs, screenshots, or any extra information that will help us investigate.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **Reference links**

        - Figma: https://www.figma.com/design/v9ECAmLYs2pam1wguh3HUS/Gardens-V2-UI?node-id=1-25&t=HMdvUpdbEzxPdDPZ-1
        - GitHub repository: https://github.com/1Hive/gardens-v2
