blank_issues_enabled: false
contact_links:
  - name: Bug
    url: https://github.com/1Hive/gardens-v2/issues/new?template=bug.yml
    about: Report a bug or unexpected behavior.
  - name: Story
    url: https://github.com/1Hive/gardens-v2/issues/new?template=story.yml
    about: Capture a product or user story.
  - name: Task
    url: https://github.com/1Hive/gardens-v2/issues/new?template=task.yml
    about: Track a general engineering or operational task.
