name: Frontend
description: Track a UI or frontend development task for Gardens V2.
labels: ["🎨 frontend"]
projects: ["1Hive/17"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for web or UI-related tasks such as component updates, UX improvements, or visual fixes.

        **Figma:** [Gardens V2 UI](https://www.figma.com/design/v9ECAmLYs2pam1wguh3HUS/Gardens-V2-UI?node-id=1-25&p=f&t=QTrkzN8ykb9AdIi6-0)  
        **Miro:** [Design Collaboration Board](https://miro.com/app/board/uXjVJF2w8YI=/)

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short headline describing the task.
      placeholder: Implement proposal card hover animation
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be built, fixed, or improved?
      placeholder: |
        Update the proposal card layout to align with latest Figma specs.
        Include transitions and responsive tweaks for mobile.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Define when this task can be considered done.
      placeholder: |
        - Matches Figma layout exactly
        - No console errors in dev tools
        - Works in Chrome, Firefox, and Safari
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation details
      description: Optional notes about libraries, routes, or affected modules.
      placeholder: |
        - Uses Tailwind and DaisyUI components
        - Updates `/app/(proposals)/components/ProposalCard.tsx`
    validations:
      required: false

  - type: textarea
    id: resources
    attributes:
      label: References or assets
      description: Include links to mockups, issues, or branches.
      placeholder: |
        - Related issue: #123
        - Figma frame: https://www.figma.com/file/...
        - PR: (to be added)
    validations:
      required: false
