name: Story
description: Capture a product or user story for the Gardens app.
title: "As a [user], I want [feature] so that [benefit]"
type: "Feature"
projects: ["1Hive/20"]
body:
  - type: markdown
    attributes:
      value: |
        Outline the user problem, desired outcome, and acceptance criteria so the team can scope and implement the story effectively.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a short title or theme for the story.
      placeholder: Snapshot of user needs or outcome
    validations:
      required: true
  - type: textarea
    id: business-context
    attributes:
      label: Business context
      description: Why does this story matter now? Include goals, constraints, or related OKRs.
      placeholder: This unlocks...
    validations:
      required: true
  - type: textarea
    id: user-value
    attributes:
      label: User value
      description: Who benefits from this story and why?
      placeholder: As a ... I want ... so that ...
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Detail the main scenarios, flows, or UI changes.
      placeholder: List the key requirements here...
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: Provide clear criteria that must be met for this story to be complete.
      placeholder: Given ... when ... then ...
    validations:
      required: true
  - type: textarea
    id: success-metrics
    attributes:
      label: Success metrics
      description: How will we measure that this story achieved the desired outcome?
      placeholder: Adoption, activation, retention targets...
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Link related issues, designs, or technical blockers.
      placeholder: Depends on issue #123...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any supporting notes, mockups, or open questions.
    validations:
      required: false
  - type: textarea
    id: stakeholders
    attributes:
      label: Stakeholders
      description: List the decision makers, reviewers, or teams to keep in sync.
      placeholder: PM, design, dev lead...
    validations:
      required: false
  - type: textarea
    id: risks
    attributes:
      label: Risks and open questions
      description: Capture known risks, assumptions, or questions to resolve.
    validations:
      required: false
  - type: checkboxes
    id: focus-areas
    attributes:
      label: Focus areas
      description: Select the relevant work areas.
      options:
        - label: "🎨 frontend"
        - label: "🔗 subgraph"
        - label: "🔧 contracts"
        - label: "👩‍🎨 design"
        - label: "🧪 tests"
  - type: markdown
    attributes:
      value: |
        **Reference links**

        - Figma: https://www.figma.com/design/v9ECAmLYs2pam1wguh3HUS/Gardens-V2-UI?node-id=1-25&t=HMdvUpdbEzxPdDPZ-1
        - GitHub repository: https://github.com/1Hive/gardens-v2
