name: Task
description: Track a general engineering or operational task.
title: ""
type: "Task"
projects: ["1Hive/17"]
body:
  - type: markdown
    attributes:
      value: |
        Provide enough detail so anyone can pick up this task, understand the desired outcome, and know when it is complete.
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the relative urgency.
      options:
        - P0 – time sensitive or blocking launch
        - P1 – important but not blocking
        - P2 – nice to have or follow up
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Outline the work to be done, relevant context, or implementation plan.
      placeholder: Steps, notes, edge cases, or resources...
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: Define how we will know this task is finished.
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Include notes, links, or considerations that help with execution.
    validations:
      required: false
  - type: checkboxes
    id: focus-areas
    attributes:
      label: Focus areas
      description: Select the relevant work areas.
      options:
        - label: "🎨 frontend"
        - label: "🔗 subgraph"
        - label: "🔧 contracts"
        - label: "👩‍🎨 design"
        - label: "🧪 tests"
  - type: markdown
    attributes:
      value: |
        **Reference links**

        - Figma: https://www.figma.com/design/v9ECAmLYs2pam1wguh3HUS/Gardens-V2-UI?node-id=1-25&t=HMdvUpdbEzxPdDPZ-1
        - GitHub repository: https://github.com/1Hive/gardens-v2
