name: "Code Review by Gemini AI"
on:
  issue_comment:
    types:
      - created
      - updated

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Put a reaction to the comment
        if: ${{ github.event.issue.pull_request && github.event.comment.body == '!ai' }}
        run: gh api graphql --silent --raw-field query="mutation AddReaction {addReaction(input:{subjectId:\"$NODE_ID\",content:EYES}){reaction{content}subject{id}}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ID: ${{ github.event.comment.node_id }}
      - name: Fetch PR details using GitHub API
        if: ${{ github.event.issue.pull_request && github.event.comment.body == '!ai' }}
        id: pr-details
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.payload.issue.number;
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            return pr.data;
      - name: "Get diff of the pull request"
        if: ${{ github.event.issue.pull_request && github.event.comment.body == '!ai' }}
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: "${{ steps.pr-details.outputs.head.ref }}"
          PULL_REQUEST_BASE_REF: "${{ steps.pr-details.outputs.base.ref }}"
        run: |-
          echo "PULL_REQUEST_HEAD_REF: $PULL_REQUEST_HEAD_REF"
          echo "PULL_REQUEST_BASE_REF: $PULL_REQUEST_BASE_REF"
          # Only include changes to .ts, .tsx, and .sol files in the diff
          git diff "origin/${{ env.PULL_REQUEST_BASE_REF }}" -- '*.ts' '*.tsx' '*.sol' > "diff.txt"
          {
            echo "pull_request_diff<<EOF"; 
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT # save the filtered diff to an output variable

      - uses: rubensflinco/gemini-code-review-action@1.0.5
        name: "Code Review by Gemini AI"
        if: ${{ github.event.issue.pull_request && github.event.comment.body == '!ai' }}
        continue-on-error: true
        id: review
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ steps.pr-details.outputs.number }}
          git_commit_hash: ${{ steps.pr-details.outputs.head.sha }}
          model: "gemini-1.5-pro-latest"
          pull_request_diff: |-
            ${{ steps.get_diff.outputs.pull_request_diff }}
          pull_request_chunk_size: "3500"
          extra_prompt: |-
            Only review files with extensions: .ts, .tsx, .sol
            Focus your review on code logic, security vulnerabilities, and potential improvements in these files.
          log_level: "DEBUG"
