name: "Code Review by Gemini AI"
on:
  pull_request:
jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: "Get diff of the pull request"
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
          PULL_REQUEST_BASE_REF: "${{ github.event.pull_request.base.ref }}"
        run: |-
          git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}" # fetch the branch with changes
          git fetch origin "${{ env.PULL_REQUEST_BASE_REF }}" # fetch the target branch
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}" # switch to the branch with changes
          git diff "origin/${{ env.PULL_REQUEST_BASE_REF }}" > "diff.txt" # generate a diff
          {
            echo "pull_request_diff<<EOF"; 
            cat "diff.txt";
            echo 'EOF';
          } >> $GITHUB_OUTPUT # save the diff to an output variable
      - uses: rubensflinco/gemini-code-review-action@1.0.5
        name: "Code Review by Gemini AI"
        continue-on-error: true
        id: review
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }}
          github_pull_request_number: ${{ github.event.pull_request.number }}
          git_commit_hash: ${{ github.event.pull_request.head.sha }}
          model: "gemini-1.0-pro"
          pull_request_diff: |-
            ${{ steps.get_diff.outputs.pull_request_diff }}
          pull_request_chunk_size: "3500" # chunk size is important to avoid exceeding the API limits
          extra_prompt: |-
            Ignore json files
          log_level: "DEBUG"
